dist: xenial
language: c
addons:
  apt:
    packages:
    - lcov
    - linux-libc-dev
    - libuv1-dev
    - btrfs-progs
    - xfsprogs
    - zfsutils-linux
compiler:
  - clang
  - gcc
before_script:
  - git clone --depth 1 https://github.com/edlund/amalgamate.git
  - export PATH=$PATH:$PWD/amalgamate
script:
  - autoreconf -i
  - ./configure --enable-example --enable-debug --enable-code-coverage --enable-sanitize
  - ./test/lib/fs.sh setup
  - make check CFLAGS=-O0
               RAFT_TMP_TMPFS=./tmp/tmpfs
               RAFT_TMP_EXT4=./tmp/ext4
               RAFT_TMP_BTRFS=./tmp/btrfs
               RAFT_TMP_XFS=./tmp/xfs
               RAFT_TMP_ZFS=./tmp/zfs
    || (cat ./test-suite.log && false)
  - if [ $TRAVIS_COMPILER = gcc ]; then make code-coverage-capture; fi
  - ./test/lib/fs.sh teardown
after_success:
  - bash <(curl -s https://codecov.io/bash) -G "./src*"
