dist: xenial
language: c
addons:
  apt:
    packages:
    - lcov
    - linux-libc-dev
    - libuv1-dev
    - xfsprogs
    - zfsutils-linux
compiler:
  - clang
  - gcc
script:
  - autoreconf -i
  - ./configure --disable-uv --enable-debug --enable-code-coverage --enable-sanitize
  - ./test/lib/fs.sh setup
  - CFLAGS=-O0
  - make
  - make check || cat ./test-suite.log
  - if [ $TRAVIS_COMPILER = gcc ]; then make code-coverage-capture; fi
  - ./test/lib/fs.sh teardown
after_success:
  - bash <(curl -s https://codecov.io/bash) -G "./src*"
