language: c
before_install:
  - sudo add-apt-repository ppa:dqlite-maintainers/master -y
  - sudo apt-get update -q
  - sudo apt-get install libuv1-dev -y
compiler:
  - clang
  - gcc
script:
  - autoreconf -i
  - ./configure --enable-debug --enable-coverage --enable-uv --enable-example
  - make
  - make ./unit-test
  - make ./integration-test
  - ./unit-test
  - ./integration-test
after_success:
  - bash <(curl -s https://codecov.io/bash) -G "./src*"
